name: Build

on: [push, pull_request, workflow_dispatch]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NuGetDirectory: ${{ github.workspace }}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.dotnet.name }}
    runs-on: ${{ matrix.platform.os }}
    permissions:
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows x64, os: windows-2025 }
        - { name: Ubuntu x64, os: ubuntu-24.04 }
        - { name: macOS arm64, os: macos-15 }
        dotnet:
        - { name: .NET 8, version: '8.0.x' }
        - { name: .NET 9, version: '9.0.x' }
        - { name: .NET 10, version: '10.0.x' }

    steps:
    - name: Checkout HTML Renderer
      uses: actions/checkout@v6

    - name: Setup .NET ${{ matrix.dotnet.version }} SDK
      id: setup-dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ matrix.dotnet.version }}
    - name: Enforce SDK Version
      run: dotnet new globaljson --sdk-version ${{ steps.setup-dotnet.outputs.dotnet-version }} --force
    - name: Verify SDK Installation
      run: dotnet --info

    - name: Restore Dependencies
      run: dotnet restore Source/HtmlRenderer.sln

    - name: Build
      run: dotnet build Source/HtmlRenderer.sln --configuration Release --no-restore

    - name: Create HtmlRenderer.Core NuGet package
      run: dotnet pack Source/HtmlRenderer/HtmlRenderer.csproj --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg --no-build --verbosity normal --output ${{ env.NuGetDirectory }}

    - name: Create HtmlRenderer.PdfSharp NuGet package
      run: dotnet pack Source/HtmlRenderer.PdfSharp/HtmlRenderer.PdfSharp.csproj --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg --no-build --verbosity normal --output ${{ env.NuGetDirectory }}

    - name: Create HtmlRenderer.WinForms NuGet package
      run: dotnet pack Source/HtmlRenderer.WinForms/HtmlRenderer.WinForms.csproj --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg --no-build --verbosity normal --output ${{ env.NuGetDirectory }}

    - name: Create HtmlRenderer.WPF NuGet package
      run: dotnet pack Source/HtmlRenderer.WPF/HtmlRenderer.WPF.csproj --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg --no-build --verbosity normal --output ${{ env.NuGetDirectory }}

    - name: Upload NuGet package artifacts
      uses: actions/upload-artifact@v5
      with:
        name: "HTML Renderer (${{ matrix.platform.name }} ${{ matrix.dotnet.name }})"
        path: ${{ env.NuGetDirectory }}/*.*nupkg

    - name: NuGet Login
      if: startsWith(github.ref, 'refs/tags/') && matrix.dotnet.name == '.NET 8' && runner.os == 'Windows'
      uses: NuGet/login@v1
      id: login
      with:
        user: eXpl0it3r
    
    - name: NuGet Push
      if: startsWith(github.ref, 'refs/tags/') && matrix.dotnet.name == '.NET 8' && runner.os == 'Windows'
      run: |
        foreach ($file in (Get-ChildItem ${{ env.NuGetDirectory }} -Recurse -Include *.*nupkg)) {
          dotnet nuget push $file --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
        }
